using System;
using PetitMoteur3D.Input;

namespace PetitMoteur3D;

internal static class KeyExtensions
{
    /// <summary>
    /// Translates a Silk.NET.Input.Key to an ImGuiNET.ImGuiKey.
    /// </summary>
    /// <param name="key">The Silk.NET.Input.Key to translate.</param>
    /// <returns>The corresponding ImGuiNET.ImGuiKey.</returns>
    /// <exception cref="NotImplementedException">When the key has not been implemented yet.</exception>
    public static ImGuiNET.ImGuiKey ToImGui(this Silk.NET.Input.Key key)
    {
        return key switch
        {
            Silk.NET.Input.Key.Tab => ImGuiNET.ImGuiKey.Tab,
            Silk.NET.Input.Key.Left => ImGuiNET.ImGuiKey.LeftArrow,
            Silk.NET.Input.Key.Right => ImGuiNET.ImGuiKey.RightArrow,
            Silk.NET.Input.Key.Up => ImGuiNET.ImGuiKey.UpArrow,
            Silk.NET.Input.Key.Down => ImGuiNET.ImGuiKey.DownArrow,
            Silk.NET.Input.Key.PageUp => ImGuiNET.ImGuiKey.PageUp,
            Silk.NET.Input.Key.PageDown => ImGuiNET.ImGuiKey.PageDown,
            Silk.NET.Input.Key.Home => ImGuiNET.ImGuiKey.Home,
            Silk.NET.Input.Key.End => ImGuiNET.ImGuiKey.End,
            Silk.NET.Input.Key.Insert => ImGuiNET.ImGuiKey.Insert,
            Silk.NET.Input.Key.Delete => ImGuiNET.ImGuiKey.Delete,
            Silk.NET.Input.Key.Backspace => ImGuiNET.ImGuiKey.Backspace,
            Silk.NET.Input.Key.Space => ImGuiNET.ImGuiKey.Space,
            Silk.NET.Input.Key.Enter => ImGuiNET.ImGuiKey.Enter,
            Silk.NET.Input.Key.Escape => ImGuiNET.ImGuiKey.Escape,
            Silk.NET.Input.Key.Apostrophe => ImGuiNET.ImGuiKey.Apostrophe,
            Silk.NET.Input.Key.Comma => ImGuiNET.ImGuiKey.Comma,
            Silk.NET.Input.Key.Minus => ImGuiNET.ImGuiKey.Minus,
            Silk.NET.Input.Key.Period => ImGuiNET.ImGuiKey.Period,
            Silk.NET.Input.Key.Slash => ImGuiNET.ImGuiKey.Slash,
            Silk.NET.Input.Key.Semicolon => ImGuiNET.ImGuiKey.Semicolon,
            Silk.NET.Input.Key.Equal => ImGuiNET.ImGuiKey.Equal,
            Silk.NET.Input.Key.LeftBracket => ImGuiNET.ImGuiKey.LeftBracket,
            Silk.NET.Input.Key.BackSlash => ImGuiNET.ImGuiKey.Backslash,
            Silk.NET.Input.Key.RightBracket => ImGuiNET.ImGuiKey.RightBracket,
            Silk.NET.Input.Key.GraveAccent => ImGuiNET.ImGuiKey.GraveAccent,
            Silk.NET.Input.Key.CapsLock => ImGuiNET.ImGuiKey.CapsLock,
            Silk.NET.Input.Key.ScrollLock => ImGuiNET.ImGuiKey.ScrollLock,
            Silk.NET.Input.Key.NumLock => ImGuiNET.ImGuiKey.NumLock,
            Silk.NET.Input.Key.PrintScreen => ImGuiNET.ImGuiKey.PrintScreen,
            Silk.NET.Input.Key.Pause => ImGuiNET.ImGuiKey.Pause,
            Silk.NET.Input.Key.Keypad0 => ImGuiNET.ImGuiKey.Keypad0,
            Silk.NET.Input.Key.Keypad1 => ImGuiNET.ImGuiKey.Keypad1,
            Silk.NET.Input.Key.Keypad2 => ImGuiNET.ImGuiKey.Keypad2,
            Silk.NET.Input.Key.Keypad3 => ImGuiNET.ImGuiKey.Keypad3,
            Silk.NET.Input.Key.Keypad4 => ImGuiNET.ImGuiKey.Keypad4,
            Silk.NET.Input.Key.Keypad5 => ImGuiNET.ImGuiKey.Keypad5,
            Silk.NET.Input.Key.Keypad6 => ImGuiNET.ImGuiKey.Keypad6,
            Silk.NET.Input.Key.Keypad7 => ImGuiNET.ImGuiKey.Keypad7,
            Silk.NET.Input.Key.Keypad8 => ImGuiNET.ImGuiKey.Keypad8,
            Silk.NET.Input.Key.Keypad9 => ImGuiNET.ImGuiKey.Keypad9,
            Silk.NET.Input.Key.KeypadDecimal => ImGuiNET.ImGuiKey.KeypadDecimal,
            Silk.NET.Input.Key.KeypadDivide => ImGuiNET.ImGuiKey.KeypadDivide,
            Silk.NET.Input.Key.KeypadMultiply => ImGuiNET.ImGuiKey.KeypadMultiply,
            Silk.NET.Input.Key.KeypadSubtract => ImGuiNET.ImGuiKey.KeypadSubtract,
            Silk.NET.Input.Key.KeypadAdd => ImGuiNET.ImGuiKey.KeypadAdd,
            Silk.NET.Input.Key.KeypadEnter => ImGuiNET.ImGuiKey.KeypadEnter,
            Silk.NET.Input.Key.KeypadEqual => ImGuiNET.ImGuiKey.KeypadEqual,
            Silk.NET.Input.Key.ShiftLeft => ImGuiNET.ImGuiKey.LeftShift,
            Silk.NET.Input.Key.ControlLeft => ImGuiNET.ImGuiKey.LeftCtrl,
            Silk.NET.Input.Key.AltLeft => ImGuiNET.ImGuiKey.LeftAlt,
            Silk.NET.Input.Key.SuperLeft => ImGuiNET.ImGuiKey.LeftSuper,
            Silk.NET.Input.Key.ShiftRight => ImGuiNET.ImGuiKey.RightShift,
            Silk.NET.Input.Key.ControlRight => ImGuiNET.ImGuiKey.RightCtrl,
            Silk.NET.Input.Key.AltRight => ImGuiNET.ImGuiKey.RightAlt,
            Silk.NET.Input.Key.SuperRight => ImGuiNET.ImGuiKey.RightSuper,
            Silk.NET.Input.Key.Menu => ImGuiNET.ImGuiKey.Menu,
            Silk.NET.Input.Key.Number0 => ImGuiNET.ImGuiKey._0,
            Silk.NET.Input.Key.Number1 => ImGuiNET.ImGuiKey._1,
            Silk.NET.Input.Key.Number2 => ImGuiNET.ImGuiKey._2,
            Silk.NET.Input.Key.Number3 => ImGuiNET.ImGuiKey._3,
            Silk.NET.Input.Key.Number4 => ImGuiNET.ImGuiKey._4,
            Silk.NET.Input.Key.Number5 => ImGuiNET.ImGuiKey._5,
            Silk.NET.Input.Key.Number6 => ImGuiNET.ImGuiKey._6,
            Silk.NET.Input.Key.Number7 => ImGuiNET.ImGuiKey._7,
            Silk.NET.Input.Key.Number8 => ImGuiNET.ImGuiKey._8,
            Silk.NET.Input.Key.Number9 => ImGuiNET.ImGuiKey._9,
            Silk.NET.Input.Key.A => ImGuiNET.ImGuiKey.A,
            Silk.NET.Input.Key.B => ImGuiNET.ImGuiKey.B,
            Silk.NET.Input.Key.C => ImGuiNET.ImGuiKey.C,
            Silk.NET.Input.Key.D => ImGuiNET.ImGuiKey.D,
            Silk.NET.Input.Key.E => ImGuiNET.ImGuiKey.E,
            Silk.NET.Input.Key.F => ImGuiNET.ImGuiKey.F,
            Silk.NET.Input.Key.G => ImGuiNET.ImGuiKey.G,
            Silk.NET.Input.Key.H => ImGuiNET.ImGuiKey.H,
            Silk.NET.Input.Key.I => ImGuiNET.ImGuiKey.I,
            Silk.NET.Input.Key.J => ImGuiNET.ImGuiKey.J,
            Silk.NET.Input.Key.K => ImGuiNET.ImGuiKey.K,
            Silk.NET.Input.Key.L => ImGuiNET.ImGuiKey.L,
            Silk.NET.Input.Key.M => ImGuiNET.ImGuiKey.M,
            Silk.NET.Input.Key.N => ImGuiNET.ImGuiKey.N,
            Silk.NET.Input.Key.O => ImGuiNET.ImGuiKey.O,
            Silk.NET.Input.Key.P => ImGuiNET.ImGuiKey.P,
            Silk.NET.Input.Key.Q => ImGuiNET.ImGuiKey.Q,
            Silk.NET.Input.Key.R => ImGuiNET.ImGuiKey.R,
            Silk.NET.Input.Key.S => ImGuiNET.ImGuiKey.S,
            Silk.NET.Input.Key.T => ImGuiNET.ImGuiKey.T,
            Silk.NET.Input.Key.U => ImGuiNET.ImGuiKey.U,
            Silk.NET.Input.Key.V => ImGuiNET.ImGuiKey.V,
            Silk.NET.Input.Key.W => ImGuiNET.ImGuiKey.W,
            Silk.NET.Input.Key.X => ImGuiNET.ImGuiKey.X,
            Silk.NET.Input.Key.Y => ImGuiNET.ImGuiKey.Y,
            Silk.NET.Input.Key.Z => ImGuiNET.ImGuiKey.Z,
            Silk.NET.Input.Key.F1 => ImGuiNET.ImGuiKey.F1,
            Silk.NET.Input.Key.F2 => ImGuiNET.ImGuiKey.F2,
            Silk.NET.Input.Key.F3 => ImGuiNET.ImGuiKey.F3,
            Silk.NET.Input.Key.F4 => ImGuiNET.ImGuiKey.F4,
            Silk.NET.Input.Key.F5 => ImGuiNET.ImGuiKey.F5,
            Silk.NET.Input.Key.F6 => ImGuiNET.ImGuiKey.F6,
            Silk.NET.Input.Key.F7 => ImGuiNET.ImGuiKey.F7,
            Silk.NET.Input.Key.F8 => ImGuiNET.ImGuiKey.F8,
            Silk.NET.Input.Key.F9 => ImGuiNET.ImGuiKey.F9,
            Silk.NET.Input.Key.F10 => ImGuiNET.ImGuiKey.F10,
            Silk.NET.Input.Key.F11 => ImGuiNET.ImGuiKey.F11,
            Silk.NET.Input.Key.F12 => ImGuiNET.ImGuiKey.F12,
            Silk.NET.Input.Key.F13 => ImGuiNET.ImGuiKey.F13,
            Silk.NET.Input.Key.F14 => ImGuiNET.ImGuiKey.F14,
            Silk.NET.Input.Key.F15 => ImGuiNET.ImGuiKey.F15,
            Silk.NET.Input.Key.F16 => ImGuiNET.ImGuiKey.F16,
            Silk.NET.Input.Key.F17 => ImGuiNET.ImGuiKey.F17,
            Silk.NET.Input.Key.F18 => ImGuiNET.ImGuiKey.F18,
            Silk.NET.Input.Key.F19 => ImGuiNET.ImGuiKey.F19,
            Silk.NET.Input.Key.F20 => ImGuiNET.ImGuiKey.F20,
            Silk.NET.Input.Key.F21 => ImGuiNET.ImGuiKey.F21,
            Silk.NET.Input.Key.F22 => ImGuiNET.ImGuiKey.F22,
            Silk.NET.Input.Key.F23 => ImGuiNET.ImGuiKey.F23,
            Silk.NET.Input.Key.F24 => ImGuiNET.ImGuiKey.F24,
            _ => throw new NotImplementedException(),
        };
    }

    /// <summary>
    /// Translates a Key to an ImGuiNET.ImGuiKey.
    /// </summary>
    /// <param name="key">The Key to translate.</param>
    /// <returns>The corresponding ImGuiNET.ImGuiKey.</returns>
    /// <exception cref="NotImplementedException">When the key has not been implemented yet.</exception>
    public static ImGuiNET.ImGuiKey ToImGui(this Key key)
    {
        return key switch
        {
            Key.Tab => ImGuiNET.ImGuiKey.Tab,
            Key.Left => ImGuiNET.ImGuiKey.LeftArrow,
            Key.Right => ImGuiNET.ImGuiKey.RightArrow,
            Key.Up => ImGuiNET.ImGuiKey.UpArrow,
            Key.Down => ImGuiNET.ImGuiKey.DownArrow,
            Key.PageUp => ImGuiNET.ImGuiKey.PageUp,
            Key.PageDown => ImGuiNET.ImGuiKey.PageDown,
            Key.Home => ImGuiNET.ImGuiKey.Home,
            Key.End => ImGuiNET.ImGuiKey.End,
            Key.Insert => ImGuiNET.ImGuiKey.Insert,
            Key.Delete => ImGuiNET.ImGuiKey.Delete,
            Key.Backspace => ImGuiNET.ImGuiKey.Backspace,
            Key.Space => ImGuiNET.ImGuiKey.Space,
            Key.Enter => ImGuiNET.ImGuiKey.Enter,
            Key.Escape => ImGuiNET.ImGuiKey.Escape,
            Key.Apostrophe => ImGuiNET.ImGuiKey.Apostrophe,
            Key.Comma => ImGuiNET.ImGuiKey.Comma,
            Key.Minus => ImGuiNET.ImGuiKey.Minus,
            Key.Period => ImGuiNET.ImGuiKey.Period,
            Key.Slash => ImGuiNET.ImGuiKey.Slash,
            Key.Semicolon => ImGuiNET.ImGuiKey.Semicolon,
            Key.Equal => ImGuiNET.ImGuiKey.Equal,
            Key.LeftBracket => ImGuiNET.ImGuiKey.LeftBracket,
            Key.BackSlash => ImGuiNET.ImGuiKey.Backslash,
            Key.RightBracket => ImGuiNET.ImGuiKey.RightBracket,
            Key.GraveAccent => ImGuiNET.ImGuiKey.GraveAccent,
            Key.CapsLock => ImGuiNET.ImGuiKey.CapsLock,
            Key.ScrollLock => ImGuiNET.ImGuiKey.ScrollLock,
            Key.NumLock => ImGuiNET.ImGuiKey.NumLock,
            Key.PrintScreen => ImGuiNET.ImGuiKey.PrintScreen,
            Key.Pause => ImGuiNET.ImGuiKey.Pause,
            Key.Keypad0 => ImGuiNET.ImGuiKey.Keypad0,
            Key.Keypad1 => ImGuiNET.ImGuiKey.Keypad1,
            Key.Keypad2 => ImGuiNET.ImGuiKey.Keypad2,
            Key.Keypad3 => ImGuiNET.ImGuiKey.Keypad3,
            Key.Keypad4 => ImGuiNET.ImGuiKey.Keypad4,
            Key.Keypad5 => ImGuiNET.ImGuiKey.Keypad5,
            Key.Keypad6 => ImGuiNET.ImGuiKey.Keypad6,
            Key.Keypad7 => ImGuiNET.ImGuiKey.Keypad7,
            Key.Keypad8 => ImGuiNET.ImGuiKey.Keypad8,
            Key.Keypad9 => ImGuiNET.ImGuiKey.Keypad9,
            Key.KeypadDecimal => ImGuiNET.ImGuiKey.KeypadDecimal,
            Key.KeypadDivide => ImGuiNET.ImGuiKey.KeypadDivide,
            Key.KeypadMultiply => ImGuiNET.ImGuiKey.KeypadMultiply,
            Key.KeypadSubtract => ImGuiNET.ImGuiKey.KeypadSubtract,
            Key.KeypadAdd => ImGuiNET.ImGuiKey.KeypadAdd,
            Key.KeypadEnter => ImGuiNET.ImGuiKey.KeypadEnter,
            Key.KeypadEqual => ImGuiNET.ImGuiKey.KeypadEqual,
            Key.ShiftLeft => ImGuiNET.ImGuiKey.LeftShift,
            Key.ControlLeft => ImGuiNET.ImGuiKey.LeftCtrl,
            Key.AltLeft => ImGuiNET.ImGuiKey.LeftAlt,
            Key.SuperLeft => ImGuiNET.ImGuiKey.LeftSuper,
            Key.ShiftRight => ImGuiNET.ImGuiKey.RightShift,
            Key.ControlRight => ImGuiNET.ImGuiKey.RightCtrl,
            Key.AltRight => ImGuiNET.ImGuiKey.RightAlt,
            Key.SuperRight => ImGuiNET.ImGuiKey.RightSuper,
            Key.Menu => ImGuiNET.ImGuiKey.Menu,
            Key.Number0 => ImGuiNET.ImGuiKey._0,
            Key.Number1 => ImGuiNET.ImGuiKey._1,
            Key.Number2 => ImGuiNET.ImGuiKey._2,
            Key.Number3 => ImGuiNET.ImGuiKey._3,
            Key.Number4 => ImGuiNET.ImGuiKey._4,
            Key.Number5 => ImGuiNET.ImGuiKey._5,
            Key.Number6 => ImGuiNET.ImGuiKey._6,
            Key.Number7 => ImGuiNET.ImGuiKey._7,
            Key.Number8 => ImGuiNET.ImGuiKey._8,
            Key.Number9 => ImGuiNET.ImGuiKey._9,
            Key.A => ImGuiNET.ImGuiKey.A,
            Key.B => ImGuiNET.ImGuiKey.B,
            Key.C => ImGuiNET.ImGuiKey.C,
            Key.D => ImGuiNET.ImGuiKey.D,
            Key.E => ImGuiNET.ImGuiKey.E,
            Key.F => ImGuiNET.ImGuiKey.F,
            Key.G => ImGuiNET.ImGuiKey.G,
            Key.H => ImGuiNET.ImGuiKey.H,
            Key.I => ImGuiNET.ImGuiKey.I,
            Key.J => ImGuiNET.ImGuiKey.J,
            Key.K => ImGuiNET.ImGuiKey.K,
            Key.L => ImGuiNET.ImGuiKey.L,
            Key.M => ImGuiNET.ImGuiKey.M,
            Key.N => ImGuiNET.ImGuiKey.N,
            Key.O => ImGuiNET.ImGuiKey.O,
            Key.P => ImGuiNET.ImGuiKey.P,
            Key.Q => ImGuiNET.ImGuiKey.Q,
            Key.R => ImGuiNET.ImGuiKey.R,
            Key.S => ImGuiNET.ImGuiKey.S,
            Key.T => ImGuiNET.ImGuiKey.T,
            Key.U => ImGuiNET.ImGuiKey.U,
            Key.V => ImGuiNET.ImGuiKey.V,
            Key.W => ImGuiNET.ImGuiKey.W,
            Key.X => ImGuiNET.ImGuiKey.X,
            Key.Y => ImGuiNET.ImGuiKey.Y,
            Key.Z => ImGuiNET.ImGuiKey.Z,
            Key.F1 => ImGuiNET.ImGuiKey.F1,
            Key.F2 => ImGuiNET.ImGuiKey.F2,
            Key.F3 => ImGuiNET.ImGuiKey.F3,
            Key.F4 => ImGuiNET.ImGuiKey.F4,
            Key.F5 => ImGuiNET.ImGuiKey.F5,
            Key.F6 => ImGuiNET.ImGuiKey.F6,
            Key.F7 => ImGuiNET.ImGuiKey.F7,
            Key.F8 => ImGuiNET.ImGuiKey.F8,
            Key.F9 => ImGuiNET.ImGuiKey.F9,
            Key.F10 => ImGuiNET.ImGuiKey.F10,
            Key.F11 => ImGuiNET.ImGuiKey.F11,
            Key.F12 => ImGuiNET.ImGuiKey.F12,
            Key.F13 => ImGuiNET.ImGuiKey.F13,
            Key.F14 => ImGuiNET.ImGuiKey.F14,
            Key.F15 => ImGuiNET.ImGuiKey.F15,
            Key.F16 => ImGuiNET.ImGuiKey.F16,
            Key.F17 => ImGuiNET.ImGuiKey.F17,
            Key.F18 => ImGuiNET.ImGuiKey.F18,
            Key.F19 => ImGuiNET.ImGuiKey.F19,
            Key.F20 => ImGuiNET.ImGuiKey.F20,
            Key.F21 => ImGuiNET.ImGuiKey.F21,
            Key.F22 => ImGuiNET.ImGuiKey.F22,
            Key.F23 => ImGuiNET.ImGuiKey.F23,
            Key.F24 => ImGuiNET.ImGuiKey.F24,
            _ => throw new NotImplementedException(),
        };
    }
}
